### ISSUE TITLE
Interface with Distances.jl

### ISSUE THREAD

**Issue by matbesancon** [mirkobunse/EarthMoversDistance.jl#1]
Would it be interesting to define a struct `EarthMoverDistance <: Distances.Metric` and implement the `Distances` interface?

This would allow users to leverage the same interface `r = evaluate(EarthMover(base_dist), x, y)`

**Comment by mirkobunse** [comment]
Thanks for the hint, I'll dig into it :+1:

**Comment by mirkobunse** [comment]
Let me mark this issue solved, as I just pushed this feature into the master branch.

Note that the new type is called `EarthMovers` and it takes as an argument either a `Function` or another distance (`PreMetric`) from Distances.jl. The short-hand is accordingly `earthmovers(a, b, ground_distance::Union{Function, PreMetric})`.
